version: "3"
services:
  app:
    container_name: containerize_app_1
    image: containerize_app:latest
    build: ./app
    volumes:
          - "./app/:/usr/src/app"
          - "./nginx/files/localhost.crt:/conf/app.crt"
          - "./nginx/files/localhost.key:/conf/app.key"
    deploy:
      resources:
        limits:
          memory: 256M

  nginx:
    container_name: containerize_nginx_1
    image: containerize_nginx:latest
    build: ./nginx
    volumes:
          - "./nginx/files/localhost.crt:/etc/nginx/ssl/app.crt"
          - "./nginx/files/localhost.key:/etc/nginx/ssl/app.key"
    ports:
      - "443:8443"
      - "80:8080"
    deploy:
      resources:
        limits:
          memory: 256M